import { prisma } from '@/lib/prisma'
import { Card } from '@/components/ui'
import { plantName, fmtDate } from '@/lib/utils'
import Link from 'next/link'
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string,status?:string,type?:string,sport?:string}>}){
 const sp=await searchParams; const q=(sp.q||'').trim(); const status=sp.status||''; const type=sp.type||''; const sport=sp.sport||''
 const instances=await prisma.plantInstance.findMany({where:{AND:[status?{status}: {}, type?{instanceType:type}: {}, sport?{sportStatus:sport}: {}, q?{OR:[{plantId:{contains:q}},{location:{contains:q}},{source:{contains:q}},{stockNumber:{contains:q}},{plantDefinition:{OR:[{genus:{contains:q}},{species:{contains:q}},{cultivarName:{contains:q}}]}}]}:{}]},include:{plantDefinition:true},orderBy:{plantId:'asc'}})
 const defs=await prisma.plantDefinition.findMany({where:q?{OR:[{genus:{contains:q}},{species:{contains:q}},{cultivarName:{contains:q}},{description:{contains:q}},{notes:{contains:q}}]}:{},include:{_count:{select:{instances:true}}},orderBy:{genus:'asc'}})
 return <div className='space-y-6'><h2 className='text-3xl font-bold'>Search / Filter</h2><Card><form className='grid gap-3 md:grid-cols-5'><input className='rounded-lg border px-3 py-2 md:col-span-2' name='q' placeholder='Search plant ID, cultivar, source, notes…' defaultValue={q}/><select className='rounded-lg border px-3 py-2' name='status' defaultValue={status}><option value=''>Any status</option><option>ACTIVE</option><option>ARCHIVED</option></select><select className='rounded-lg border px-3 py-2' name='type' defaultValue={type}><option value=''>Any type</option><option>MOTHER</option><option>PROPAGATION</option></select><select className='rounded-lg border px-3 py-2' name='sport' defaultValue={sport}><option value=''>Any sport status</option><option>NONE</option><option>SUSPECTED</option><option>CANDIDATE</option><option>STABLE</option><option>UNSTABLE</option><option>REGISTERED</option></select><button className='rounded-xl bg-green-800 px-4 py-2 text-sm font-medium text-white md:col-span-5'>Search</button></form></Card><div className='grid gap-4 lg:grid-cols-2'><Card><h3 className='mb-3 font-bold'>Plant instances</h3>{instances.map(i=><p key={i.id} className='border-t py-2 text-sm'><Link className='font-bold underline' href={`/instances/${i.id}`}>{i.plantId}</Link> · {plantName(i.plantDefinition)} · {i.status} · {fmtDate(i.propagationDate || i.acquisitionDate)}</p>)}</Card><Card><h3 className='mb-3 font-bold'>Plant definitions</h3>{defs.map(d=><p key={d.id} className='border-t py-2 text-sm'><Link className='font-bold underline' href={`/plants/${d.id}/edit`}>{plantName(d)}</Link> · {d._count.instances} instance(s)</p>)}</Card></div></div>
}
