import { prisma } from '@/lib/prisma'
import { updatePlantDefinition, deletePlantDefinition } from '@/app/actions'
import { Card, Field, TextArea, Button } from '@/components/ui'
import { ConfirmDeleteButton } from '@/components/ConfirmDeleteButton'
export default async function EditPlant({params}:{params:Promise<{id:string}>}){
 const {id}=await params
 const [p,bodies]=await Promise.all([prisma.plantDefinition.findUniqueOrThrow({where:{id},include:{_count:{select:{instances:true}}}}),prisma.governingBody.findMany({orderBy:{name:'asc'}})])
 return <div className='space-y-6'><h2 className='text-3xl font-bold'>Edit Plant Definition</h2><Card><form action={updatePlantDefinition} className='grid gap-3 md:grid-cols-2'><input type='hidden' name='id' value={id}/><Field label='Genus' name='genus' required defaultValue={p.genus}/><Field label='Species' name='species' required defaultValue={p.species}/><Field label='Hybrid notation' name='hybridNotation' defaultValue={p.hybridNotation}/><Field label='Cultivar name' name='cultivarName' defaultValue={p.cultivarName}/><Field label='Cultivar registration number' name='cultivarRegistrationNumber' defaultValue={p.cultivarRegistrationNumber}/><label className='grid gap-1 text-sm font-medium'>Governing body<select className='rounded-lg border px-3 py-2 font-normal' name='governingBodyId' defaultValue={p.governingBodyId || ''}><option value=''>—</option>{bodies.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><TextArea label='Description' name='description' defaultValue={p.description}/><TextArea label='Notes' name='notes' defaultValue={p.notes}/><Button className='md:col-span-2'>Save changes</Button></form></Card><Card><h3 className='font-bold'>Delete</h3><p className='mb-3 text-sm'>Delete is only safe when no instances use this definition. Current instances: {p._count.instances}</p><form action={deletePlantDefinition}><input type='hidden' name='id' value={id}/><ConfirmDeleteButton title='Delete plant definition?' message={`This will permanently delete ${p.genus} ${p.species}${p.cultivarName ? ` '${p.cultivarName}'` : ''}. Related instances may also be affected.`} confirmLabel='Delete definition'>Delete plant definition</ConfirmDeleteButton></form></Card></div>
}
