import Link from 'next/link'
import { redactDomainEvent } from '@/app/event-actions'
import { Button, Card, TextArea } from '@/components/ui'
import { requireServerAdmin } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { formatDateTime } from '@/lib/time'

export default async function ServerEventDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireServerAdmin()
  const { id } = await params
  const event = await prisma.domainEvent.findUniqueOrThrow({ where: { id }, include: { actor: { select: { email: true } }, ignoredBy: { select: { email: true } }, processingHistory: { orderBy: { startedAt: 'desc' } }, supersededByEvent: true } })
  return <div className="space-y-5"><div className="flex justify-between gap-3"><div><h2 className="text-3xl font-bold">{event.eventType}</h2><p className="text-sm text-stone-600">{event.id}</p></div><Link className="rounded border px-3 py-2 text-sm font-semibold" href="/server/events">Event Processing</Link></div><Card><dl className="grid gap-3 text-sm md:grid-cols-3"><div><dt>Status</dt><dd className="font-semibold">{event.processingStatus}</dd></div><div><dt>Occurred</dt><dd>{formatDateTime(event.occurredAt)}</dd></div><div><dt>Recorded</dt><dd>{formatDateTime(event.recordedAt)}</dd></div><div><dt>Actor</dt><dd>{event.actor?.email || 'System'}</dd></div><div><dt>Visibility</dt><dd>{event.visibility}</dd></div><div><dt>Attempts</dt><dd>{event.processingAttempts}</dd></div></dl>{event.lastProcessingError && <pre className="mt-4 overflow-auto rounded bg-red-950 p-3 text-xs text-red-50">{event.lastProcessingError}</pre>}{event.redactedAt ? <p className="mt-4 rounded border border-red-200 bg-red-50 p-3">Payload redacted at {formatDateTime(event.redactedAt)}.</p> : <><h3 className="mt-5 font-semibold">Summary</h3><pre className="mt-2 overflow-auto rounded bg-stone-950 p-3 text-xs text-stone-100">{JSON.stringify(event.summaryJson, null, 2)}</pre><details className="mt-3"><summary className="cursor-pointer font-semibold">Payload and metadata</summary><pre className="mt-2 overflow-auto rounded bg-stone-950 p-3 text-xs text-stone-100">{JSON.stringify({ payload: event.payloadJson, metadata: event.metadataJson }, null, 2)}</pre></details></>}</Card><Card><h3 className="font-semibold">Processing history</h3><div className="mt-3 grid gap-2">{event.processingHistory.map((attempt) => <div key={attempt.id} className="rounded border p-3 text-sm"><span className="font-semibold">Attempt {attempt.attempt} · {attempt.status}</span><span className="ml-2 text-stone-500">{formatDateTime(attempt.startedAt)}</span>{attempt.error && <p className="mt-1 text-xs text-red-800">{attempt.error}</p>}</div>)}{event.processingHistory.length === 0 && <p className="text-sm text-stone-600">Not processed yet.</p>}</div></Card>{!event.redactedAt && <Card><details><summary className="cursor-pointer font-semibold text-red-800">Redact sensitive payload</summary><form action={redactDomainEvent} className="mt-4 grid gap-3"><input type="hidden" name="eventId" value={event.id}/><TextArea label="Redaction reason" name="reason" required/><Button className="w-fit">Record redaction</Button></form></details></Card>}</div>
}
