import { prisma } from '@/lib/prisma'
import { createPlantInstance } from '@/app/actions'
import { Card, Field, TextArea, Button } from '@/components/ui'
import { plantName } from '@/lib/utils'
import Link from 'next/link'
export default async function Instances(){
 const [instances,defs]=await Promise.all([prisma.plantInstance.findMany({where:{status:'ACTIVE'},include:{plantDefinition:true},orderBy:{plantId:'asc'}}),prisma.plantDefinition.findMany({orderBy:{genus:'asc'}})])
 return <div className='space-y-6'><h2 className='text-3xl font-bold'>Plant Instances</h2><Card><form action={createPlantInstance} className='grid gap-3 md:grid-cols-2'><label className='grid gap-1 text-sm font-medium'>Plant definition<select className='rounded-lg border px-3 py-2 font-normal' name='plantDefinitionId' required>{defs.map(d=><option key={d.id} value={d.id}>{plantName(d)}</option>)}</select></label><Field label='Plant ID' name='plantId' required/><label className='grid gap-1 text-sm font-medium'>Type<select className='rounded-lg border px-3 py-2 font-normal' name='instanceType'><option>MOTHER</option><option>PROPAGATION</option></select></label><Field label='Location' name='location'/><Field label='Acquisition date' name='acquisitionDate' type='date'/><Field label='Propagation date' name='propagationDate' type='date'/><Field label='Source/propagator' name='source'/><Field label='Distributor' name='distributor'/><Field label='Stock number' name='stockNumber'/><Field label='Purchase price' name='purchasePrice' type='number'/><label className='text-sm font-medium'><input type='checkbox' name='isSportCandidate'/> Sport candidate</label><label className='grid gap-1 text-sm font-medium'>Sport status<select className='rounded-lg border px-3 py-2 font-normal' name='sportStatus'><option>NONE</option><option>SUSPECTED</option><option>CANDIDATE</option><option>STABLE</option><option>UNSTABLE</option><option>REGISTERED</option></select></label><TextArea label='Sport description' name='sportDescription'/><Button className='md:col-span-2'>Create instance</Button></form></Card><div className='grid gap-3'>{instances.map(i=><Card key={i.id}><div className='flex items-center justify-between'><div><Link className='text-lg font-bold underline' href={`/instances/${i.id}`}>{i.plantId}</Link><p className='text-sm'>{plantName(i.plantDefinition)} · {i.instanceType} · {i.location || 'No location'}</p></div><div className='flex gap-2'><Link className='rounded-xl border px-3 py-2 text-sm' href={`/instances/${i.id}/edit`}>Edit</Link><Link className='rounded-xl border px-3 py-2 text-sm' href={`/labels/${i.id}`}>Label</Link></div></div></Card>)}</div></div>
}
