import { prisma } from '@/lib/prisma'
import { updatePropagationEvent, deletePropagationEvent } from '@/app/actions'
import { Card, Field, TextArea, Button, DangerButton } from '@/components/ui'
import { dateInput } from '@/lib/utils'
export default async function EditPropagation({params}:{params:Promise<{id:string}>}){
 const {id}=await params
 const e=await prisma.propagationEvent.findUniqueOrThrow({where:{id},include:{parents:{include:{parentPlantInstance:true}},children:{include:{childPlantInstance:true}}}})
 return <div className='space-y-6'><h2 className='text-3xl font-bold'>Edit Propagation Event</h2><Card><form action={updatePropagationEvent} className='grid gap-3 md:grid-cols-2'><input type='hidden' name='id' value={id}/><label className='grid gap-1 text-sm font-medium'>Method<select className='rounded-lg border px-3 py-2 font-normal' name='method' defaultValue={e.method}><option>LEAF</option><option>CUTTING</option><option>RHIZOME_SPLIT</option><option>DIVISION</option><option>SEED</option><option>TISSUE_CULTURE</option><option>RUNNER</option><option>OTHER</option></select></label><Field label='Date' name='date' type='date' required defaultValue={dateInput(e.date)}/><label className='grid gap-1 text-sm font-medium'>Success status<select className='rounded-lg border px-3 py-2 font-normal' name='successStatus' defaultValue={e.successStatus}><option>PENDING</option><option>SUCCESS</option><option>PARTIAL</option><option>FAILED</option></select></label><div className='text-sm'><b>Parents</b><br/>{e.parents.map(p=><div key={p.id}>{p.parentRole}: {p.parentPlantInstance.plantId}</div>)}</div><div className='text-sm'><b>Children</b><br/>{e.children.map(c=><div key={c.id}>{c.childPlantInstance.plantId}</div>)}</div><TextArea label='Notes' name='notes' defaultValue={e.notes}/><Button className='md:col-span-2'>Save changes</Button></form></Card><Card><h3 className='font-bold'>Delete</h3><p className='mb-3 text-sm'>Deletes the propagation event and parent/child links, but not the child plant instances.</p><form action={deletePropagationEvent}><input type='hidden' name='id' value={id}/><DangerButton>Delete event</DangerButton></form></Card></div>
}
