import { PrismaClient } from '@prisma/client'
import { randomBytes, scryptSync } from 'crypto'
import { ensureStarterSubstrates } from '../lib/substrates'
const prisma = new PrismaClient()
function hashPassword(password:string){ const salt=randomBytes(16).toString('hex'); const hash=scryptSync(password,salt,64).toString('hex'); return `${salt}:${hash}` }
async function main(){
 await prisma.auditLog.deleteMany(); await prisma.session.deleteMany(); await prisma.collectionMembership.deleteMany(); await prisma.collectionInvitation.deleteMany(); await prisma.sportStabilityRecord.deleteMany(); await prisma.propagationChild.deleteMany(); await prisma.parentageLink.deleteMany(); await prisma.propagationEvent.deleteMany(); await prisma.bloomEvent.deleteMany(); await prisma.note.deleteMany(); await prisma.photo.deleteMany(); await prisma.plantHusbandryOverride.deleteMany(); await prisma.plantInstance.deleteMany(); await prisma.plantHusbandryGuide.deleteMany(); await prisma.plantDefinition.deleteMany(); await prisma.governingBody.deleteMany(); await prisma.followNotification.deleteMany(); await prisma.follow.deleteMany(); await prisma.reminderDelivery.deleteMany(); await prisma.reminder.deleteMany(); await prisma.collection.deleteMany(); await prisma.user.deleteMany();
 const admin=await prisma.user.create({data:{email:'admin@axildb.com',emailVerifiedAt:new Date(),passwordHash:hashPassword('password'),role:'SERVER_ADMIN'}})
 const collection=await prisma.collection.create({data:{name:'AxilDB',slug:'axildb',visibility:'PRIVATE',status:'ACTIVE',description:'Default AxilDB collection.'}})
 await ensureStarterSubstrates(prisma,collection.id,admin.id)
 await prisma.collectionMembership.create({data:{collectionId:collection.id,userId:admin.id,role:'MANAGER',status:'ACTIVE'}})
 const palmstreet=await prisma.distributor.create({data:{collectionId:collection.id,name:'Palmstreet',normalizedName:'palmstreet',distributorType:'MARKETPLACE'}})
 const etsy=await prisma.distributor.create({data:{collectionId:collection.id,name:'Etsy',normalizedName:'etsy',distributorType:'MARKETPLACE'}})
 await prisma.distributor.create({data:{collectionId:collection.id,name:"Lowe's",normalizedName:"lowe's",distributorType:'BIG_BOX_STORE',outlets:{create:{collectionId:collection.id,name:'Glen Burnie Store',normalizedName:'glen burnie store',outletType:'PHYSICAL_BRANCH',city:'Glen Burnie'}}}})
 await prisma.seller.create({data:{collectionId:collection.id,name:'Aerial Roots',normalizedName:'aerial roots',kind:'ORGANIZATION',storefronts:{create:[{collectionId:collection.id,distributorId:palmstreet.id,handleOrName:'@AerialRootsFL',normalizedName:'@aerialrootsfl',storefrontType:'MARKETPLACE_SELLER'},{collectionId:collection.id,distributorId:etsy.id,handleOrName:'Aerial Roots Tropicals',normalizedName:'aerial roots tropicals',storefrontType:'MARKETPLACE_SELLER'},{collectionId:collection.id,handleOrName:'aerialroots.com',normalizedName:'aerialroots.com',storefrontType:'DIRECT_ONLINE_STORE'}]}}})
 await prisma.seller.create({data:{collectionId:collection.id,name:'Jane Smith',normalizedName:'jane smith',kind:'PERSON',description:'Private seller demo record.'}})
 await prisma.seller.create({data:{collectionId:collection.id,name:'Rare Plant Nursery',normalizedName:'rare plant nursery',kind:'ORGANIZATION',storefronts:{create:{collectionId:collection.id,distributorId:etsy.id,handleOrName:'RarePlantNursery',normalizedName:'rareplantnursery',storefrontType:'MARKETPLACE_SELLER'}}}})
 await prisma.seller.create({data:{collectionId:collection.id,name:'Spring Society Vendor',normalizedName:'spring society vendor',kind:'ORGANIZATION',storefronts:{create:{collectionId:collection.id,handleOrName:'Spring show table 12',normalizedName:'spring show table 12',storefrontType:'SHOW_VENDOR'}}}})
 const avsa=await prisma.governingBody.create({data:{collectionId:collection.id,name:'African Violet Society of America',abbreviation:'AVSA',website:'https://africanvioletsocietyofamerica.org'}})
 const chimera=await prisma.plantDefinition.create({data:{collectionId:collection.id,genus:'Saintpaulia',species:'ionantha',cultivarName:'Demo Starfall',authority:'H.Wendl.',cultivarRegistrationNumber:'DEMO-001',governingBodyId:avsa.id,confidence:'PROBABLE',provisionalTaxon:'Saintpaulia ionantha',identificationStatus:'PROVISIONAL',description:'Demo cultivar for seeded development data.',aliases:{create:[{collectionId:collection.id,name:'African violet',aliasType:'COMMON_NAME',confidence:'CONFIRMED',source:'Common horticultural use'},{collectionId:collection.id,name:'Streptocarpus sect. Saintpaulia Demo Starfall',aliasType:'SYNONYM',confidence:'UNCERTAIN',source:'Taxonomic review placeholder'}]}}})
 await prisma.plantHusbandryGuide.create({data:{collectionId:collection.id,plantDefinitionId:chimera.id,summaryWater:'Keep evenly moist',summaryLight:'Bright indirect light',summaryToxicity:'Generally non-toxic to pets',summaryCare:'Warm shelf culture with steady moisture and gentle fertilizer.',wateringCadence:'Water when the surface begins to dry, usually weekly under lights.',wateringMoistureLevel:'Evenly moist, never soggy.',lightIntensity:'Bright indirect light or moderate grow lights.',humidityRange:'40-60% is comfortable.',mediumPreferred:'Light African violet mix with extra perlite.',fertilizationStrength:'Dilute balanced fertilizer.',fertilizationFrequency:'Every 2-4 weeks while actively growing.',propagationMethods:'Leaf cuttings are reliable.',propagationDifficulty:'Easy to moderate.',toxicityPets:'Generally considered non-toxic.',bloomSeason:'Intermittent under stable indoor conditions.',bloomRebloomTendency:'Reblooms readily when healthy.',growthHabit:'Compact rosette.',reviewStatus:'REVIEWED'}})
 const mother=await prisma.plantInstance.create({data:{collectionId:collection.id,plantDefinitionId:chimera.id,plantId:'AV-001',instanceType:'MOTHER',location:'Plant shelf A',acquisitionDate:new Date('2026-04-12'),acquisitionLabel:'African violet Demo Starfall',source:'Demo Nursery',distributor:'Local plant sale',stockNumber:'DN-42',purchasePrice:'18.00'}})
 const event=await prisma.propagationEvent.create({data:{collectionId:collection.id,method:'LEAF',date:new Date('2026-05-01'),successStatus:'SUCCESS',notes:'One leaf pull, two viable plantlets.',parents:{create:{parentPlantInstanceId:mother.id,parentRole:'SOURCE_PARENT'}}}})
 const child1=await prisma.plantInstance.create({data:{collectionId:collection.id,plantDefinitionId:chimera.id,plantId:'AV-001-P1',instanceType:'PROPAGATION',location:'Propagation tray',propagationDate:new Date('2026-05-01')}})
 const child2=await prisma.plantInstance.create({data:{collectionId:collection.id,plantDefinitionId:chimera.id,plantId:'AV-001-P2',instanceType:'PROPAGATION',location:'Propagation tray',propagationDate:new Date('2026-05-01'),isSportCandidate:true,sportStatus:'SUSPECTED',sportDescription:'Variegation appears stronger than mother.'}})
 await prisma.propagationChild.createMany({data:[{propagationEventId:event.id,childPlantInstanceId:child1.id},{propagationEventId:event.id,childPlantInstanceId:child2.id}]})
 const e2=await prisma.propagationEvent.create({data:{collectionId:collection.id,method:'LEAF',date:new Date('2026-05-20'),successStatus:'SUCCESS',parents:{create:{parentPlantInstanceId:child2.id,parentRole:'SOURCE_PARENT'}}}})
 const sportChild=await prisma.plantInstance.create({data:{collectionId:collection.id,plantDefinitionId:chimera.id,plantId:'AV-001-P2-A',instanceType:'PROPAGATION',location:'Sport tray',propagationDate:new Date('2026-05-20'),isSportCandidate:true,sportStatus:'CANDIDATE',sportDescription:'Sport descendant showing same variegation.'}})
 await prisma.propagationChild.create({data:{propagationEventId:e2.id,childPlantInstanceId:sportChild.id}})
 await prisma.sportStabilityRecord.create({data:{plantInstanceId:sportChild.id,propagationEventId:e2.id,propagatedTrue:true,generationNumber:3,notes:'Demo record: third true sport propagation.'}})
 await prisma.bloomEvent.create({data:{collectionId:collection.id,plantInstanceId:mother.id,bloomStartDate:new Date('2026-05-10'),peakBloomDate:new Date('2026-05-14'),flowerCount:7,firstBloom:false,notes:'Strong bloom cycle.'}})
 await prisma.note.create({data:{collectionId:collection.id,entityType:'PLANT_INSTANCE',entityId:mother.id,note:'Healthy mother specimen. Good candidate for continued leaf propagation.'}})
}
main().finally(()=>prisma.$disconnect())
