import { prisma } from '@/lib/prisma'
import { Card, Field, TextArea, Button, LinkButton } from '@/components/ui'
import { createSportStabilityRecord } from '@/app/actions'
import { plantName } from '@/lib/utils'
import Link from 'next/link'
export default async function SportReview(){
 const sports=await prisma.plantInstance.findMany({where:{OR:[{isSportCandidate:true},{sportStatus:{not:'NONE'}}]},include:{plantDefinition:true,sportRecords:{include:{propagationEvent:true},orderBy:{generationNumber:'desc'}}},orderBy:{updatedAt:'desc'}})
 const events=await prisma.propagationEvent.findMany({include:{children:{include:{childPlantInstance:true}}},orderBy:{date:'desc'}})
 return <div className='space-y-6'><h2 className='text-3xl font-bold'>Sport Stability Review</h2><p className='text-sm text-stone-600'>Review suspected sports, log true-to-type propagation records, and start the cultivar wizard when a line reaches three true propagations.</p>{sports.map(s=>{ const trueCount=s.sportRecords.filter(r=>r.propagatedTrue).length; const eligible=s.sportRecords.some(r=>r.propagatedTrue && r.generationNumber>=3) || trueCount>=3; return <Card key={s.id}><div className='flex items-start justify-between gap-4'><div><Link className='text-lg font-bold underline' href={`/instances/${s.id}`}>{s.plantId}</Link><p className='text-sm'>{plantName(s.plantDefinition)} · {s.sportStatus}</p><p className='text-sm'>{s.sportDescription}</p><p className='mt-2 text-sm font-medium'>True records: {trueCount}</p></div>{eligible && <LinkButton href={`/sports/${s.id}/cultivar`}>Create cultivar</LinkButton>}</div><form action={createSportStabilityRecord} className='mt-4 grid gap-3 md:grid-cols-2'><input type='hidden' name='plantInstanceId' value={s.id}/><input type='hidden' name='back' value='/sports'/><label className='grid gap-1 text-sm font-medium'>Propagation event<select className='rounded-lg border px-3 py-2 font-normal' name='propagationEventId'>{events.map(e=><option key={e.id} value={e.id}>{e.date.toLocaleDateString()} · {e.method} · {e.children.map(c=>c.childPlantInstance.plantId).join(', ')}</option>)}</select></label><Field label='Generation number' name='generationNumber' type='number' defaultValue={trueCount+1}/><label className='text-sm font-medium'><input type='checkbox' name='propagatedTrue'/> Propagated true</label><TextArea label='Notes/evidence' name='notes'/><Button className='md:col-span-2'>Add stability record</Button></form>{s.sportRecords.length>0 && <div className='mt-4 border-t pt-3 text-sm'>{s.sportRecords.map(r=><p key={r.id}>Gen {r.generationNumber}: {r.propagatedTrue?'true':'not true'} · {r.notes}</p>)}</div>}</Card>})}</div>
}
