import { recordBatchTreatmentApplications } from '@/app/treatment-actions'
import { Button, Card, Field, LinkButton, Select, TextArea } from '@/components/ui'
import { collectionPath, requireCollectionLogger } from '@/lib/collections'
import { descendantLocationIds } from '@/lib/locations'
import { prisma } from '@/lib/prisma'
import { labelizeTreatment, treatmentApplicationMethods, treatmentDoseUnits, treatmentTargetAreas } from '@/lib/treatments'
import { plantName } from '@/lib/utils'

export default async function BatchTreatmentPage({ searchParams }: { searchParams: Promise<{ location?: string; nested?: string; condition?: string; severity?: string; quarantine?: string; q?: string }> }) {
  const { collection } = await requireCollectionLogger()
  const sp = await searchParams
  const [locations, allPlants, treatments] = await Promise.all([
    prisma.location.findMany({ where: { collectionId: collection.id, status: 'ACTIVE' }, orderBy: [{ sortOrder: 'asc' }, { name: 'asc' }] }),
    prisma.plantInstance.findMany({ where: { collectionId: collection.id, status: 'ACTIVE' }, include: { plantDefinition: true, currentLocation: true, conditions: { where: { status: { in: ['OPEN', 'IMPROVING'] } } }, quarantines: { where: { status: 'ACTIVE' }, take: 1 } }, orderBy: { plantId: 'asc' }, take: 1000 }),
    prisma.treatmentDefinition.findMany({ where: { collectionId: collection.id, active: true }, include: { products: { include: { product: true }, orderBy: { sortOrder: 'asc' } } }, orderBy: { name: 'asc' } }),
  ])
  const locationIds = sp.location ? new Set([sp.location, ...(sp.nested === '1' ? descendantLocationIds(sp.location, locations) : [])]) : null
  const q = (sp.q || '').trim().toLowerCase()
  const plants = allPlants.filter((plant) => (!locationIds || (plant.currentLocationId && locationIds.has(plant.currentLocationId)))
    && (!sp.condition || plant.conditions.some((condition) => condition.category === sp.condition))
    && (!sp.severity || plant.conditions.some((condition) => condition.severity === sp.severity))
    && (sp.quarantine !== '1' || plant.quarantines.length > 0)
    && (!q || `${plant.plantId} ${plantName(plant.plantDefinition)}`.toLowerCase().includes(q)))
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-3xl font-bold">Batch treatment application</h2><p className="mt-1 text-sm text-stone-600">Filter and select plants, then create a distinct historical application for each specimen.</p></div><LinkButton href={collectionPath(collection.slug, '/treatments')}>Treatment Management</LinkButton></header>
    <Card><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label="Search" name="q" defaultValue={sp.q} /><Select label="Location" name="location" defaultValue={sp.location || ''}><option value="">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.code} · {location.name}</option>)}</Select><Select label="Condition" name="condition" defaultValue={sp.condition || ''}><option value="">Any condition</option>{['PESTS', 'DISEASE', 'FUNGAL', 'ROOT_ISSUE', 'NUTRIENT_ISSUE', 'WILTING', 'YELLOWING_LEAVES', 'CRISPY_LEAVES', 'SUNBURN', 'MECHANICAL_DAMAGE', 'OTHER'].map((item) => <option key={item}>{item}</option>)}</Select><Select label="Severity" name="severity" defaultValue={sp.severity || ''}><option value="">Any severity</option>{['LOW', 'MODERATE', 'HIGH', 'CRITICAL'].map((item) => <option key={item}>{item}</option>)}</Select><label className="inline-flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" name="nested" value="1" defaultChecked={sp.nested === '1'} />Include nested locations</label><label className="inline-flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" name="quarantine" value="1" defaultChecked={sp.quarantine === '1'} />Quarantine only</label><Button className="w-fit lg:col-span-6">Filter plants</Button></form></Card>
    <form action={recordBatchTreatmentApplications} className="space-y-4"><input type="hidden" name="collectionSlug" value={collection.slug} /><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} />
      <Card><h3 className="font-serif text-xl font-semibold">Shared application values</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="Treatment" name="treatmentDefinitionId" required><option value="">Select treatment</option>{treatments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Field label="Applied at" name="appliedAt" type="datetime-local" /><Field label="Dose" name="doseAmount" type="number" min="0" step="any" /><Select label="Dose unit" name="doseUnit"><option value="">Not recorded</option>{treatmentDoseUnits.map((item) => <option key={item}>{labelizeTreatment(item)}</option>)}</Select><Field label="Water (mL)" name="waterVolumeMl" type="number" min="0" step="any" /><Field label="Strength" name="strength" /><Select label="Method" name="applicationMethod"><option value="">Not recorded</option>{treatmentApplicationMethods.map((item) => <option key={item}>{labelizeTreatment(item)}</option>)}</Select><Select label="Target area" name="targetArea"><option value="">Not recorded</option>{treatmentTargetAreas.map((item) => <option key={item}>{labelizeTreatment(item)}</option>)}</Select><TextArea label="Shared notes" name="notes" wrapperClassName="sm:col-span-2 lg:col-span-4" /><TextArea label="Required reason when overriding a blocking interval warning" name="intervalOverrideNote" wrapperClassName="sm:col-span-2 lg:col-span-4" /></div></Card>
      <Card><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-serif text-xl font-semibold">Plants</h3><p className="text-sm text-stone-600">{plants.length} visible. Matching conditions and pending plan steps are linked automatically.</p></div></div><div className="mt-3 grid gap-2 md:grid-cols-2">{plants.map((plant) => <div key={plant.id} className="rounded-md border border-stone-200 bg-white/60 p-3"><label className="flex items-start gap-3"><input className="mt-1" type="checkbox" name="plantInstanceId" value={plant.id} /><span className="min-w-0"><strong className="block">{plant.plantId}</strong><span className="block text-sm">{plantName(plant.plantDefinition)}</span><span className="block text-xs text-stone-600">{plant.currentLocation ? `${plant.currentLocation.code} · ${plant.currentLocation.name}` : 'No location'} · {plant.conditions.map((condition) => `${labelizeTreatment(condition.category)} (${labelizeTreatment(condition.severity)})`).join(', ') || 'No open condition'}{plant.quarantines.length ? ' · Quarantine' : ''}</span></span></label><details className="mt-2 pl-7"><summary className="cursor-pointer text-xs font-semibold underline">Override shared values</summary><div className="mt-2 grid gap-2 sm:grid-cols-2"><Field label="Dose override" name={`doseAmount:${plant.id}`} type="number" min="0" step="any" /><Field label="Notes override" name={`notes:${plant.id}`} /></div></details></div>)}{plants.length === 0 && <p className="text-sm text-stone-600">No plants match these filters.</p>}</div></Card>
      <Card className="border-amber-200 bg-amber-50"><p className="text-sm"><strong>Review:</strong> Defaults do not imply actual use. The server rechecks condition suitability, tag cautions, active blooms, quarantine state, and treatment intervals for each selected plant.</p><label className="mt-3 inline-flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="acknowledgeWarnings" required />I reviewed the selected plants, safety warnings, product label, and application values.</label><Button className="mt-3 w-full sm:w-auto" disabled={!plants.length}>Record batch applications</Button></Card>
    </form>
  </div>
}
